import { AlertCircle, CheckCircle2, FileWarning, Send } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useAuth } from '../context/AuthContext';
import api from '../services/api';
import '../order-pages.css';

export default function Complaints() {
  const { user } = useAuth(); const admin = user?.role === 'admin';
  const [complaints, setComplaints] = useState([]); const [form, setForm] = useState({ subject: '', category: 'Delivery issue', orderId: '', message: '' }); const [status, setStatus] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); setError(''); return api.get('/complaints').then(({ data }) => setComplaints(Array.isArray(data) ? data : [])).catch((err) => { setComplaints([]); setError(err.response?.data?.message || 'Unable to load complaints. Please start the backend server.'); }).finally(() => setLoading(false)); };
  useEffect(() => { load(); }, []);
  const submit = async (event) => { event.preventDefault(); setStatus(''); setError(''); try { await api.post('/complaints', form); setForm({ subject: '', category: 'Delivery issue', orderId: '', message: '' }); setStatus('Complaint submitted successfully'); load(); } catch (err) { setError(err.response?.data?.message || 'Could not submit complaint'); } };
  const update = (complaint, next) => api.patch(`/complaints/${complaint._id}/status`, { status: next }).then(load);
  return <div className="content complaints-page"><div className="orders-hero hero-active"><div><p className="eyebrow">Support center</p><h2>{admin ? 'Complaint desk' : 'Complaints'}</h2><p>{admin ? 'Review and resolve delivery partner concerns.' : 'Tell us what went wrong and we will help.'}</p></div><div className="hero-note"><span>{admin ? 'Open cases' : 'Need help?'}</span><strong>{complaints.filter((item) => item.status !== 'Resolved').length} active complaints</strong></div></div>{!admin && <section className="panel complaint-form-card"><div className="panel-heading"><div><h3>Submit a complaint</h3><p>Our operations team will review your request.</p></div><FileWarning size={22} /></div><form className="complaint-form" onSubmit={submit}><label>Subject<input required value={form.subject} onChange={(event) => setForm({ ...form, subject: event.target.value })} placeholder="What is the issue?" /></label><label>Category<select value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })}><option>Delivery issue</option><option>Order issue</option><option>Payment issue</option><option>Other</option></select></label><label>Order ID (optional)<input value={form.orderId} onChange={(event) => setForm({ ...form, orderId: event.target.value })} placeholder="Example: FW-1234567" /></label><label className="complaint-message">Message<textarea required rows="5" value={form.message} onChange={(event) => setForm({ ...form, message: event.target.value })} placeholder="Describe the problem in detail"></textarea></label>{status && <div className="success-message"><CheckCircle2 size={16} />{status}</div>}{error && <div className="error">{error}</div>}<button className="primary-btn" type="submit"><Send size={16} /> Submit complaint</button></form></section>}<section className="panel complaint-list"><div className="panel-heading"><div><h3>{admin ? 'All complaints' : 'Your complaint history'}</h3><p>{complaints.length} {complaints.length === 1 ? 'case' : 'cases'}</p></div></div>{complaints.length ? complaints.map((complaint) => <div className="complaint-row" key={complaint._id}><div className="complaint-icon"><AlertCircle size={18} /></div><div className="complaint-copy"><strong>{complaint.subject}</strong><small>{complaint.category}{complaint.orderId ? ` · ${complaint.orderId}` : ''}</small><p>{complaint.message}</p>{admin && <small>Submitted by {complaint.user?.name || 'User'}</small>}</div>{admin ? <select value={complaint.status} onChange={(event) => update(complaint, event.target.value)}><option>Open</option><option>In Review</option><option>Resolved</option></select> : <span className={`complaint-status ${complaint.status.toLowerCase().replace(' ', '-')}`}>{complaint.status}</span>}</div>) : <div className="empty">No complaints submitted yet.</div>}</section></div>;
}
