import { Activity, Box, CheckCircle2, Clock3, PackageCheck, Send, Truck, Users } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useAuth } from '../context/AuthContext';
import { useNavigate } from 'react-router-dom';
import api from '../services/api';
import StatCard from '../components/StatCard';
import OrderTable from '../components/OrderTable';
import { DeliveryForm, fastFood, FoodImage, indianFood } from './Landing';
export default function Dashboard() { const { user } = useAuth(); const navigate = useNavigate(); const admin = user.role === 'admin'; const [stats, setStats] = useState({}); const [category, setCategory] = useState('fast-food'); useEffect(() => { api.get(`/dashboard/${admin ? 'admin' : 'delivery'}`).then(({ data }) => setStats(data)); }, [admin]); const cards = admin ? [['Total orders', stats.totalOrders, 'ink', Box], ['Pending', stats.pending, 'amber', Clock3], ['Assigned', stats.assigned, 'blue', Truck], ['Out for delivery', stats.outForDelivery, 'orange', Activity], ['Delivered', stats.delivered, 'green', CheckCircle2], ['Delivery boys', stats.totalDeliveryBoys, 'violet', Users]] : [['Assigned orders', stats.assigned, 'blue', PackageCheck], ['Pending deliveries', stats.pending, 'amber', Clock3], ['Out for delivery', stats.outForDelivery, 'orange', Truck], ['Completed', stats.completed, 'green', CheckCircle2]]; const menu = category === 'food' ? indianFood : fastFood; const showDelivery = category === 'delivery'; return <div className="content"><div className="section-heading"><div><p className="eyebrow">{admin ? 'Today at a glance' : 'Your route at a glance'}</p><h2>Operations overview</h2></div><span className="live"><i></i>Live data</span></div><div className="stats-grid">{cards.map(([label, value, tone, Icon]) => <StatCard key={label} label={label} value={value ?? '—'} tone={tone} icon={Icon} />)}</div><section className="dashboard-food"><div className="dashboard-category-strip"><button className={category === 'fast-food' ? 'selected' : ''} onClick={() => setCategory('fast-food')}><Clock3 size={20} /><span><strong>Fast Food</strong><small>Pizza, burger and more</small></span></button><button className={category === 'food' ? 'selected' : ''} onClick={() => setCategory('food')}><PackageCheck size={20} /><span><strong>Food</strong><small>Fresh Indian favourites</small></span></button><button className={category === 'delivery' ? 'selected' : ''} onClick={() => setCategory('delivery')}><Send size={20} /><span><strong>Delivery</strong><small>Send anything anywhere</small></span></button></div><div className="dashboard-food-content"><div className="section-heading landing-heading"><div><p className="eyebrow">{showDelivery ? 'On-demand delivery' : category === 'food' ? 'Made with tradition' : 'Made for the moment'}</p><h2>{showDelivery ? 'Where should we deliver?' : category === 'food' ? 'Comfort in every plate' : 'Pick your kind of happy'}</h2></div></div>{showDelivery ? <DeliveryForm /> : <div className="food-grid">{menu.map((item) => <article className={`food-card ${item.tone}`} key={item.name}><div className="food-image" onClick={() => navigate('/payment', { state: { item } })}><FoodImage src={item.image} alt={item.name} /><span>{item.price}</span></div><div className="food-info"><div><h3>{item.name}</h3><p>{item.detail}</p></div><span className="food-arrow"><Send size={16} /></span></div></article>)}</div>}</div></section></div>; }
