import { CheckCircle2, Clock3, PackageCheck, Search, Truck } from 'lucide-react';
import { useEffect, useState } from 'react';
import api from '../services/api';
import OrderTable from '../components/OrderTable';
import '../order-pages.css';
export default function Orders({ history, active, completed, deliveryView = false }) {
	const [orders, setOrders] = useState([]); const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
	const load = () => { setLoading(true); setError(''); return api.get('/orders', { params: { search, status } }).then(({ data }) => setOrders(Array.isArray(data) ? data : [])).catch((err) => { setOrders([]); setError(err.response?.data?.message || 'Unable to load orders. Please check the server connection.'); }).finally(() => setLoading(false)); };
	useEffect(() => { load(); }, [status]);
	const update = (order, next) => api.patch(`/orders/${order._id}/status`, { status: next }).then(load);
	const visible = history || completed ? orders.filter((o) => o.status === 'Delivered') : active ? orders.filter((o) => ['Assigned', 'Picked Up', 'Out for Delivery'].includes(o.status)) : orders;
	const title = history ? 'Delivery history' : completed ? 'Completed deliveries' : active ? 'Active deliveries' : 'My orders';
	const description = history ? 'Every delivery completed across your network.' : completed ? 'A record of packages successfully delivered.' : active ? 'Packages currently moving through your route.' : 'All orders assigned to you, in one place.';
	const viewNote = history ? 'A complete record of successful handoffs.' : completed ? 'Celebrate every package delivered safely.' : active ? 'Keep each stop moving with the next status.' : 'See every package waiting for your attention.';
	const metrics = [['All orders', orders.length, PackageCheck, 'blue'], ['Waiting', orders.filter((order) => ['Pending', 'Assigned'].includes(order.status)).length, Clock3, 'amber'], ['On the way', orders.filter((order) => ['Picked Up', 'Out for Delivery'].includes(order.status)).length, Truck, 'orange'], ['Delivered', orders.filter((order) => order.status === 'Delivered').length, CheckCircle2, 'green']];
	return <div className="content delivery-orders-page"><div className={`orders-hero ${active ? 'hero-active' : completed || history ? 'hero-completed' : 'hero-orders'}`}><div><p className="eyebrow">{deliveryView ? 'Driver workspace' : 'Order intelligence'}</p><h2>{title}</h2><p>{description}</p></div><div className="hero-note"><span>{active ? 'Next stop' : completed || history ? 'Great work' : 'Your queue'}</span><strong>{viewNote}</strong></div></div><div className="order-metrics">{metrics.map(([label, value, Icon, tone]) => <div className={`order-metric ${tone}`} key={label}><span><Icon size={18} /></span><div><small>{label}</small><strong>{value}</strong></div></div>)}</div><div className="toolbar"><div className="search"><Search size={18} /><input placeholder="Search by order or customer" value={search} onChange={(e) => setSearch(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && load()} /></div>{!deliveryView && <select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All statuses</option>{['Pending', 'Assigned', 'Picked Up', 'Out for Delivery', 'Delivered', 'Cancelled'].map((item) => <option key={item}>{item}</option>)}</select>}</div><section className="panel"><div className="panel-heading"><div><h3>{active ? 'In progress' : completed || history ? 'Completed orders' : 'Assigned orders'}</h3><p>{visible.length} {visible.length === 1 ? 'order' : 'orders'} in this view</p></div></div>{loading ? <div className="orders-loading"><span></span><span></span><span></span><p>Loading your orders...</p></div> : error ? <div className="orders-error"><p>{error}</p><button className="secondary-btn" onClick={load}>Try again</button></div> : <OrderTable orders={visible} onStatus={active || (!history && !completed) ? update : undefined} />}</section></div>;
}
