import { ArrowLeft, CheckCircle2, CreditCard, MapPin, ShieldCheck } from 'lucide-react';
import { useLocation, useNavigate } from 'react-router-dom';
import { useState } from 'react';
import { FoodImage, fastFood } from './Landing';
import { useAuth } from '../context/AuthContext';
import api from '../services/api';

export default function Payment() {
  const { state } = useLocation(); const navigate = useNavigate(); const { user } = useAuth(); const [confirmed, setConfirmed] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [deliveryAddress, setDeliveryAddress] = useState(''); const item = state?.item || fastFood[0];
  const amount = Number(item.price.replace(/[^0-9.]/g, ''));
  const createOrder = async () => { if (!deliveryAddress.trim()) return setError('Please enter a delivery address'); setBusy(true); setError(''); try { await api.post('/orders', { customerName: user.name, customerPhone: user.phone, customerAddress: user.address || deliveryAddress, pickupAddress: 'FASTWAY Food Kitchen', deliveryAddress, packageDescription: item.name, packageWeight: 1, amount }); setConfirmed(true); } catch (err) { setError(err.response?.data?.message || 'Could not confirm your order'); } finally { setBusy(false); } };
  const ordersPath = user.role === 'admin' ? '/admin/orders' : '/delivery/orders';
  return <div className="payment-page"><div className="payment-shell"><button className="back-link" onClick={() => navigate(-1)}><ArrowLeft size={17} /> Back to menu</button><div className="payment-header"><p className="eyebrow">Secure checkout</p><h2>Complete your order</h2><p>Fresh food, safely packed and on its way to you.</p></div><div className="payment-layout"><section className="payment-card order-summary"><div className="payment-image"><FoodImage src={item.image} alt={item.name} /></div><div><p className="eyebrow">Your selection</p><h3>{item.name}</h3><p>{item.detail}</p><strong>{item.price}</strong></div></section><section className="payment-card payment-form"><h3>Payment details</h3><label>Card number<div className="payment-input"><CreditCard size={17} /><input required placeholder="1234  5678  9012  3456" /></div></label><div className="payment-fields"><label>Expiry<input required placeholder="MM / YY" /></label><label>CVV<input required placeholder="123" /></label></div><label>Delivery address<div className="payment-input"><MapPin size={17} /><input required value={deliveryAddress} onChange={(event) => setDeliveryAddress(event.target.value)} placeholder="Enter your full address" /></div></label>{error && <div className="error">{error}</div>}<div className="secure-note"><ShieldCheck size={16} /> Your payment information is encrypted and secure.</div><button className="pay-btn" disabled={busy} onClick={createOrder}>{busy ? 'Confirming...' : 'Pay now'} <span>{item.price}</span></button></section></div></div>{confirmed && <div className="modal-backdrop"><div className="confirm-modal"><span className="confirm-icon"><CheckCircle2 size={31} /></span><h3>Order confirmed!</h3><p>Your {item.name} order is saved and will appear in My Orders.</p><button className="primary-btn" onClick={() => navigate(ordersPath)}>View my orders <ArrowLeft size={16} /></button></div></div>}</div>;
}
